# Generated by Django 3.2.25 on 2024-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('decr', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
