# Generated by Django 3.2.25 on 2025-06-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20250620_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='addres2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
